// import './globals.css'
import { Inter, Roboto_Mono } from 'next/font/google';
import Header from "../components/Header";
import Footer from "../components/Footer"

const inter = Inter({ subsets: ['latin'] })

const roboto_mono = Roboto_Mono({subsets: ['latin']})

export const metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto_mono.className}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
